ALTER TABLE svc_verdict
  ADD COLUMN s_align NUMERIC(6,5),
  ADD COLUMN r_si    NUMERIC(6,5),
  ADD COLUMN p_si    NUMERIC(6,5),
  ADD COLUMN si_breach BOOLEAN DEFAULT FALSE,
  ADD COLUMN si_hysteresis BOOLEAN DEFAULT FALSE;
